package dev.otectus.mcaconversations.content;

import com.google.gson.JsonElement;
import com.google.gson.JsonObject;
import com.google.gson.JsonParser;
import dev.otectus.mcaconversations.conversation.BeatContract;
import dev.otectus.mcaconversations.conversation.Openness;
import dev.otectus.mcaconversations.conversation.ReplyContract;
import dev.otectus.mcaconversations.conversation.SignatureBeat;
import dev.otectus.mcaconversations.conversation.VoiceWeight;
import dev.otectus.mcaconversations.personality.Personalities;

import org.junit.jupiter.api.DisplayName;
import org.junit.jupiter.api.Test;

import java.io.IOException;
import java.nio.file.Files;
import java.nio.file.Path;
import java.util.ArrayList;
import java.util.LinkedHashMap;
import java.util.LinkedHashSet;
import java.util.List;
import java.util.Map;
import java.util.Set;
import java.util.TreeMap;
import java.util.TreeSet;
import java.util.stream.Stream;

import static org.junit.jupiter.api.Assertions.assertEquals;
import static org.junit.jupiter.api.Assertions.assertFalse;
import static org.junit.jupiter.api.Assertions.assertTrue;
import dev.otectus.mcaconversations.support.TestPaths;

/**
 * Writes the content coverage report the release ships with (spec phase 9).
 *
 * <p>Phase 9 asks for "a content coverage report in the release artifacts". The adjacency report is
 * the reading material; this is the count. It answers, in one page, the questions a release note
 * cannot answer honestly without measuring: how many conversations there are, how deep each topic
 * goes against the target its depth class sets, how much of the corpus is personality-aware, how
 * much of it can be reached by typing rather than clicking, and whether the second locale is whole.
 *
 * <p>It is generated rather than written because a hand-maintained coverage table is wrong within a
 * week, and it is asserted deterministic for the same reason the adjacency report is: the interesting
 * question is usually not "what does it say" but "what did this change do to it".
 */
class ContentCoverageReportTest {

    private static final Path REPORT_DIR = TestPaths.of("build/reports/conversations");
    private static final Path REPORT = REPORT_DIR.resolve("coverage.md");

    private static final Path DIALOGUES =
            TestPaths.of("src/main/resources/data/mcaconversations/dialogues");
    private static final Path INTENTS =
            TestPaths.of("src/main/resources/data/mcaconversations/chat_intents");
    private static final Path PROFILES =
            TestPaths.of("src/main/resources/data/mcaconversations/profession_profiles");
    private static final Path TOPICS =
            TestPaths.of("src/main/resources/data/mcaconversations/conversation_catalog/topics.json");
    /** §8.1's breadth floors, by the depth class a topic declares for itself. */
    private static final Map<String, Integer> SUBJECT_FLOOR = Map.of(
            "quick", 2, "standard", 10, "deep", 4, "relationship", 4, "service", 2);

    @Test
    @DisplayName("the content coverage report generates, counts, and is byte-identical run to run")
    void reportGenerates() throws IOException {
        String first = render();
        String second = render();
        assertEquals(first, second, "the coverage report must be deterministic so it can be diffed");
        assertFalse(first.isBlank(), "the coverage report is empty");

        Files.createDirectories(REPORT_DIR);
        Files.writeString(REPORT, first);

        // The report is only worth shipping if it actually found the corpus.
        assertTrue(first.contains("| Topic |"), "the depth table is missing");
        assertTrue(first.contains("## Personalisation"), "the personalisation section is missing");
    }

    private static String render() throws IOException {
        StringBuilder out = new StringBuilder();
        out.append("# MCA: Conversations — content coverage\n\n");
        out.append("Generated by the build. Every number here is measured from the shipped data"
                + " files, not maintained by hand.\n\n");

        coherence(out);
        depth(out);
        personalisation(out);
        frontends(out);
        return out.toString();
    }

    // --- coherence -----------------------------------------------------------

    private static void coherence(StringBuilder out) {
        List<BeatContract> beats = new ArrayList<>(ContentFixture.catalog().beats());
        List<ReplyContract> replies = new ArrayList<>(ContentFixture.catalog().replies());
        Set<String> topics = new TreeSet<>();
        beats.forEach(b -> topics.add(b.topic()));

        out.append("## Coherence\n\n");
        out.append("| Measure | Count |\n|---|---:|\n");
        out.append("| Beat contracts | ").append(beats.size()).append(" |\n");
        out.append("| Reply contracts | ").append(replies.size()).append(" |\n");
        out.append("| Topics with contracted beats | ").append(topics.size()).append(" |\n");
        out.append("| Uncontracted routes | ").append(ContentFixture.beatProblems().size())
                .append(" |\n\n");
    }

    // --- depth ---------------------------------------------------------------

    private static void depth(StringBuilder out) throws IOException {
        JsonObject catalog = JsonParser.parseString(Files.readString(TOPICS))
                .getAsJsonObject().getAsJsonObject("topics");

        Map<String, Set<String>> subjects = new TreeMap<>();
        Map<String, Set<Openness>> openness = new TreeMap<>();
        Map<String, Integer> callbacks = new TreeMap<>();
        for (BeatContract beat : ContentFixture.catalog().beats()) {
            subjects.computeIfAbsent(beat.topic(), t -> new TreeSet<>()).add(beat.subject());
            openness.computeIfAbsent(beat.topic(), t -> new TreeSet<>()).add(beat.openness());
            if (beat.callback().isPresent()) {
                callbacks.merge(beat.topic(), 1, Integer::sum);
            }
        }

        out.append("## Depth, against each topic's own target\n\n");
        out.append("| Topic | Class | Subject families | Target | Disclosure levels | Callbacks |\n");
        out.append("|---|---|---:|---:|---:|---:|\n");
        for (String name : new TreeSet<>(catalog.keySet())) {
            String depth = catalog.getAsJsonObject(name).has("depth")
                    ? catalog.getAsJsonObject(name).get("depth").getAsString() : "standard";
            int have = subjects.getOrDefault(name, Set.of()).size();
            int floor = SUBJECT_FLOOR.getOrDefault(depth, 2);
            out.append("| ").append(name)
                    .append(" | ").append(depth)
                    .append(" | ").append(have)
                    .append(" | ").append(floor)
                    .append(" | ").append(openness.getOrDefault(name, Set.of()).size())
                    .append(" | ").append(callbacks.getOrDefault(name, 0))
                    .append(" |\n");
        }
        out.append('\n');
    }

    // --- personalisation -----------------------------------------------------

    private static void personalisation(StringBuilder out) throws IOException {
        Set<String> pools = new LinkedHashSet<>();
        Set<String> signature = new TreeSet<>();
        // A pool spoken by more than one beat takes the highest tier any of them gives it: a line is
        // as important as the most important place it is used.
        Map<String, VoiceWeight> tiers = new TreeMap<>();
        for (BeatContract beat : ContentFixture.catalog().beats()) {
            pools.add(beat.say());
            if (SignatureBeat.isSignature(beat)) {
                signature.add(beat.say());
            }
            tiers.merge(beat.say(), VoiceWeight.of(beat), (a, b) -> a.weight() >= b.weight() ? a : b);
        }

        // Overlays live in their own asset namespaces: assets/mca_dialogue_<personality>/lang/.
        Path assets = TestPaths.of("src/main/resources/assets");
        Set<String> overlaid = new TreeSet<>();
        Set<String> signatureOverlaid = new TreeSet<>();
        int namespaces = 0;
        for (String prefix : Personalities.overlayPrefixes()) {
            Path file = assets.resolve("mca_dialogue_" + prefix + "/lang/en_us.json");
            if (!Files.exists(file)) {
                continue;
            }
            namespaces++;
            JsonObject doc = JsonParser.parseString(Files.readString(file)).getAsJsonObject();
            for (String key : doc.keySet()) {
                // Overlay keys read "<personality>.dialogue.<pool>/<variant>".
                if (!key.startsWith(prefix + ".dialogue.")) {
                    continue;
                }
                String pool = key.substring((prefix + ".dialogue.").length());
                int slash = pool.indexOf('/');
                if (slash > 0) {
                    pool = pool.substring(0, slash);
                }
                if (pools.contains(pool)) {
                    overlaid.add(pool);
                    if (signature.contains(pool)) {
                        signatureOverlaid.add(pool);
                    }
                }
            }
        }

        out.append("## Personalisation\n\n");
        out.append("| Measure | Count |\n|---|---:|\n");
        out.append("| Canonical personalities | ").append(Personalities.CANONICAL.size())
                .append(" |\n");
        out.append("| Overlay namespaces shipped | ").append(namespaces).append(" |\n");
        out.append("| Referenced say pools | ").append(pools.size()).append(" |\n");
        out.append("| Signature pools (section 9.3) | ").append(signature.size()).append(" |\n");
        out.append("| Signature pools with personality overlays | ")
                .append(signatureOverlaid.size()).append(" |\n");
        out.append("| Say pools with personality overlays | ").append(overlaid.size())
                .append(String.format(" (%.1f%%) |", pools.isEmpty() ? 0.0
                        : 100.0 * overlaid.size() / pools.size())).append('\n');
        // Salience-weighted coverage (spec §15.5). A signature line counts eight times a
        // farewell, so the number cannot be moved by writing twenty-one voices for
        // "see you later".
        long weighted = 0;
        long weightedCovered = 0;
        Map<VoiceWeight, int[]> byTier = new java.util.EnumMap<>(VoiceWeight.class);
        for (String pool : pools) {
            VoiceWeight tier = tiers.getOrDefault(pool, VoiceWeight.FILLER);
            weighted += tier.weight();
            int[] counts = byTier.computeIfAbsent(tier, key -> new int[2]);
            counts[1]++;
            if (overlaid.contains(pool)) {
                weightedCovered += tier.weight();
                counts[0]++;
            }
        }
        out.append("| Salience-weighted overlay coverage | ")
                .append(String.format("%.1f%% |", weighted == 0 ? 0.0
                        : 100.0 * weightedCovered / weighted)).append('\n');
        out.append('\n');

        out.append("| Voice tier | Weight | Pools | With overlays |\n|---|---:|---:|---:|\n");
        for (VoiceWeight tier : VoiceWeight.values()) {
            int[] counts = byTier.getOrDefault(tier, new int[2]);
            out.append("| ").append(tier.name().toLowerCase(java.util.Locale.ROOT))
                    .append(" | ").append(tier.weight())
                    .append(" | ").append(counts[1])
                    .append(" | ").append(counts[0])
                    .append(String.format(" (%.1f%%) |", counts[1] == 0 ? 0.0
                            : 100.0 * counts[0] / counts[1])).append('\n');
        }
        out.append('\n');
    }

    // --- frontends and locales ----------------------------------------------

    private static void frontends(StringBuilder out) throws IOException {
        int answers = 0;
        Set<String> nodes = new TreeSet<>();
        try (Stream<Path> files = Files.list(DIALOGUES)) {
            for (Path file : files.filter(p -> p.toString().endsWith(".json")).toList()) {
                nodes.add(file.getFileName().toString().replace(".json", ""));
                JsonObject page = JsonParser.parseString(Files.readString(file)).getAsJsonObject();
                if (!page.has("answers")) {
                    continue;
                }
                for (JsonElement element : page.getAsJsonArray("answers")) {
                    if (element.getAsJsonObject().has("name")) {
                        answers++;
                    }
                }
            }
        }

        int intents = 0;
        try (Stream<Path> files = Files.list(INTENTS)) {
            for (Path file : files.filter(p -> p.toString().endsWith(".json")).toList()) {
                JsonObject doc = JsonParser.parseString(Files.readString(file)).getAsJsonObject();
                if (doc.has("intents")) {
                    intents += doc.getAsJsonObject("intents").size();
                }
            }
        }

        long profiles = 0;
        if (Files.isDirectory(PROFILES)) {
            try (Stream<Path> files = Files.list(PROFILES)) {
                for (Path file : files.filter(p -> p.toString().endsWith(".json")).toList()) {
                    JsonObject doc = JsonParser.parseString(Files.readString(file)).getAsJsonObject();
                    if (doc.has("profiles")) {
                        profiles += doc.getAsJsonObject("profiles").size();
                    }
                }
            }
        }

        Map<String, String> en = ContentFixture.english();
        Map<String, String> pt = ContentFixture.readLang(ContentFixture.LANG_PT);
        Map<String, Integer> localeCounts = new LinkedHashMap<>();
        localeCounts.put("en_us", en.size());
        localeCounts.put("pt_br", pt.size());

        out.append("## Frontends, professions and locales\n\n");
        out.append("| Measure | Count |\n|---|---:|\n");
        out.append("| Question nodes | ").append(nodes.size()).append(" |\n");
        out.append("| Named answers | ").append(answers).append(" |\n");
        out.append("| Chat intents | ").append(intents).append(" |\n");
        out.append("| Profession profiles | ").append(profiles).append(" |\n");
        localeCounts.forEach((locale, count) ->
                out.append("| Lang keys, ").append(locale).append(" | ").append(count).append(" |\n"));
        out.append('\n');
        out.append("Locale key and placeholder parity is asserted exactly by `LocaleParityTest`;"
                + " the counts above are a sanity check, not the gate.\n");
    }
}
